name: Generate Snake

on:
  push:
    branches:
    - main  # Eğer başka bir branch kullanıyorsan burayı güncelle.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Generate Snake animation
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: EnesEfeTokta
          outputs: dist/snake.svg

      - name: Push Snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
